{
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.12.3"
  }
 },
 "cells": [
  {
   "cell_type": "markdown",
   "id": "title",
   "metadata": {},
   "source": [
    "# Construction du dataset Élection Présidentielle 2012 — 1er tour\n",
    "## Mise en conformité avec le modèle 2017 / 2022\n",
    "\n",
    "**Source :** Ministère de l'Intérieur via data.gouv.fr  \n",
    "**URL :** https://www.data.gouv.fr/api/1/datasets/r/adac47aa-6436-47aa-b1c0-f35882187970\n",
    "\n",
    "**Problème de fond :** En 2012, il existait **22 régions métropolitaines** (avant la réforme territoriale de 2015).  \n",
    "En 2017 et 2022, il n'en existe plus que **13** (+ Outre-mer).  \n",
    "Ce notebook télécharge les données 2012 brutes, agrège les anciennes régions vers les nouvelles, et produit un fichier au format identique aux fichiers 2017/2022.\n",
    "\n",
    "---\n",
    "### Table des correspondances anciennes → nouvelles régions (réforme 2015)\n",
    "| Nouvelles régions (2016+) | Anciennes régions (2012) |\n",
    "|---|---|\n",
    "| Auvergne-Rhône-Alpes (84) | Auvergne + Rhône-Alpes |\n",
    "| Bourgogne-Franche-Comté (27) | Bourgogne + Franche-Comté |\n",
    "| Grand Est (44) | Alsace + Champagne-Ardenne + Lorraine |\n",
    "| Hauts-de-France (32) | Nord-Pas-de-Calais + Picardie |\n",
    "| Normandie (28) | Haute-Normandie + Basse-Normandie |\n",
    "| Nouvelle-Aquitaine (75) | Aquitaine + Limousin + Poitou-Charentes |\n",
    "| Occitanie (76) | Languedoc-Roussillon + Midi-Pyrénées |\n",
    "| Bretagne (53) | Bretagne |\n",
    "| Centre-Val de Loire (24) | Centre |\n",
    "| Île-de-France (11) | Île-de-France |\n",
    "| Pays de la Loire (52) | Pays de la Loire |\n",
    "| PACA (93) | Provence-Alpes-Côte d'Azur |\n",
    "| Corse (94) | Corse |"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "md-step1",
   "metadata": {},
   "source": [
    "## Étape 1 — Imports & Téléchargement"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "imports",
   "metadata": {},
   "outputs": [],
   "source": "import pandas as pd\nimport numpy as np\nimport requests\nimport io\nimport os\nimport warnings\nwarnings.filterwarnings('ignore')\n\n# on s'assure que les dossiers existent\nos.makedirs('data_brut', exist_ok=True)\nos.makedirs('data_clean', exist_ok=True)\n\n# ----------------------------------------------------------------\n# Téléchargement du fichier XLS officiel depuis data.gouv.fr\n# Source : Ministère de l'Intérieur — Licence Ouverte\n# ----------------------------------------------------------------\nURL_2012 = 'https://www.data.gouv.fr/api/1/datasets/r/adac47aa-6436-47aa-b1c0-f35882187970'\n\nprint('Téléchargement en cours...')\nresponse = requests.get(URL_2012, timeout=60)\nresponse.raise_for_status()\nprint(f'✅ Fichier téléchargé — taille : {len(response.content)/1024:.0f} Ko')\n\n# Sauvegarde du fichier brut dans data_brut/\nwith open('data_brut/presidentielle_2012_raw.xls', 'wb') as f:\n    f.write(response.content)\nprint('✅ Fichier sauvegardé : data_brut/presidentielle_2012_raw.xls')"
  },
  {
   "cell_type": "markdown",
   "id": "md-step2",
   "metadata": {},
   "source": [
    "## Étape 2 — Exploration du fichier brut"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "explore-sheets",
   "metadata": {},
   "outputs": [],
   "source": "# Lire toutes les feuilles disponibles\nxl = pd.ExcelFile('data_brut/presidentielle_2012_raw.xls', engine='xlrd')\nprint('Feuilles disponibles :')\nfor s in xl.sheet_names:\n    print(f'  - {s}')"
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "explore-regions",
   "metadata": {},
   "outputs": [],
   "source": "# Lire la feuille régions — chercher la bonne feuille\n# Le fichier contient typiquement : Régions T1, Régions T2, Départements T1, etc.\nsheet_name = None\nfor s in xl.sheet_names:\n    if 'gion' in s.lower() and ('1' in s or 'T1' in s or 'tour' in s.lower()):\n        sheet_name = s\n        break\n\n# Si pas trouvé automatiquement, essayer la première feuille avec 'région'\nif sheet_name is None:\n    for s in xl.sheet_names:\n        if 'gion' in s.lower():\n            sheet_name = s\n            break\n\n# Fallback : première feuille\nif sheet_name is None:\n    sheet_name = xl.sheet_names[0]\n\nprint(f'Feuille utilisée : {sheet_name}')\n\n# Lecture brute\ndf_raw = pd.read_excel('data_brut/presidentielle_2012_raw.xls', sheet_name=sheet_name,\n                       engine='xlrd', header=None)\nprint(f'Dimensions brutes : {df_raw.shape}')\nprint('\\n--- 10 premières lignes ---')\ndf_raw.head(10)"
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "explore-all-sheets",
   "metadata": {},
   "outputs": [],
   "source": "# Afficher les 5 premières lignes de CHAQUE feuille pour repérer la structure\nfor s in xl.sheet_names:\n    try:\n        tmp = pd.read_excel('data_brut/presidentielle_2012_raw.xls', sheet_name=s,\n                            engine='xlrd', header=None, nrows=3)\n        print(f'\\n=== {s} === ({tmp.shape})')\n        print(tmp.to_string())\n    except Exception as e:\n        print(f'\\n=== {s} === ERREUR: {e}')"
  },
  {
   "cell_type": "markdown",
   "id": "md-step3",
   "metadata": {},
   "source": [
    "## Étape 3 — Extraction des données régions T1\n",
    "\n",
    "Le fichier du Ministère de l'Intérieur a un format multi-lignes d'en-tête.  \n",
    "On identifie la ligne contenant 'Inscrits' pour repérer le vrai header."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "parse-header",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Identifier la ligne d'en-tête (contient 'Inscrits')\n",
    "header_row = None\n",
    "for i, row in df_raw.iterrows():\n",
    "    if row.astype(str).str.contains('Inscrits', case=False, na=False).any():\n",
    "        header_row = i\n",
    "        print(f'En-tête trouvé à la ligne {i}')\n",
    "        print(row.dropna().tolist())\n",
    "        break\n",
    "\n",
    "if header_row is None:\n",
    "    print('En-tête non trouvé automatiquement — affichage des 15 premières lignes pour diagnostic')\n",
    "    print(df_raw.head(15).to_string())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "parse-data",
   "metadata": {},
   "outputs": [],
   "source": "# Recharger avec le bon header\ndf_regions_raw = pd.read_excel(\n    'data_brut/presidentielle_2012_raw.xls',\n    sheet_name=sheet_name,\n    engine='xlrd',\n    header=header_row\n)\n\nprint(f'Dimensions : {df_regions_raw.shape}')\nprint('\\nColonnes :')\nprint(df_regions_raw.columns.tolist())\nprint('\\n--- Aperçu ---')\ndf_regions_raw.head(10)"
  },
  {
   "cell_type": "markdown",
   "id": "md-step4",
   "metadata": {},
   "source": [
    "## Étape 4 — Nettoyage & Identification des régions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "clean-columns",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Renommer les colonnes proprement\n",
    "# Le fichier Ministère contient : Code région, Libellé région, Inscrits,\n",
    "# Abstentions, Votants, Blancs/Nuls, Exprimés, puis les candidats\n",
    "\n",
    "df = df_regions_raw.copy()\n",
    "\n",
    "# Supprimer les lignes entièrement vides\n",
    "df = df.dropna(how='all')\n",
    "\n",
    "# Identifier les colonnes clés par leurs noms\n",
    "cols = df.columns.astype(str).tolist()\n",
    "print('Colonnes disponibles :')\n",
    "for i, c in enumerate(cols):\n",
    "    print(f'  [{i}] {c}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "identify-candidates",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Lister les candidats 2012 au 1er tour\n",
    "CANDIDATS_2012 = [\n",
    "    'Hollande',      # PS\n",
    "    'Sarkozy',       # UMP\n",
    "    'Le Pen',        # FN  (Marine Le Pen)\n",
    "    'Melenchon',     # FG\n",
    "    'Bayrou',        # Modem\n",
    "    'Joly',          # EELV\n",
    "    'Dupont-Aignan', # DLF\n",
    "    'Poutou',        # NPA\n",
    "    'Arthaud',       # LO\n",
    "    'Cheminade'      # Solidarité et Progrès\n",
    "]\n",
    "\n",
    "print('Candidats attendus :', CANDIDATS_2012)\n",
    "print()\n",
    "\n",
    "# Chercher correspondances dans les colonnes\n",
    "for cand in CANDIDATS_2012:\n",
    "    found = [c for c in cols if cand.lower().split()[0] in c.lower()]\n",
    "    print(f'  {cand:20s} → {found}')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "md-step5",
   "metadata": {},
   "source": [
    "## Étape 5 — Reconstruction manuelle si nécessaire\n",
    "\n",
    "Le fichier du Ministère peut avoir un format complexe (multi-niveaux d'en-têtes).  \n",
    "Si la lecture automatique échoue, on reconstruit à partir des données officielles connues."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fallback-data",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ================================================================\n",
    "# DONNÉES DE RÉFÉRENCE — Résultats officiels 1er tour 2012\n",
    "# Source : Ministère de l'Intérieur\n",
    "# Périmètre : 22 ANCIENNES régions métropolitaines + Outre-mer\n",
    "#\n",
    "# Ces données sont utilisées comme FALLBACK si le parsing XLS\n",
    "# échoue, ET comme référence de validation dans tous les cas.\n",
    "# ================================================================\n",
    "\n",
    "data_2012_anciennes = {\n",
    "    # Code ancien : [Libelle, Inscrits, Abstentions, Votants, Blancs_Nuls,\n",
    "    #                Exprimes, Hollande, Sarkozy, LePen, Melenchon, Bayrou,\n",
    "    #                Joly, DupontAignan, Poutou, Arthaud, Cheminade]\n",
    "    '11': ['Île-de-France',        7168826, 1454543, 5714283, 138726, 5575557, 1820126, 1365148,  573862, 1054085,  464978, 118282, 73741, 41660, 22044,  1631],\n",
    "    '21': ['Champagne-Ardenne',    963956,  198046,  765910,  21034,  744876,  219059,  199474,  172960,  90588,   35682,  14413,  4826,  4561,  2861,   432],\n",
    "    '22': ['Picardie',             1390490, 305052,  1085438, 30073,  1055365, 309614,  270764,  268530,  138977,  39648,  15182,  5884,  4620,  2149,   997],\n",
    "    '23': ['Haute-Normandie',      1214764, 250327,  964437,  27561,  936876,  280814,  246127,  204196,  119393,  51085,  17483,  8001,  6133,  3001,   643],\n",
    "    '24': ['Centre',               1836561, 375453,  1461108, 40649,  1420459, 421248,  367764,  289714,  176175,  101028, 28706, 16519,  8981,  8561,  1763],\n",
    "    '25': ['Basse-Normandie',      1039408, 213244,  826164,  22978,  803186,  238476,  215337,  175059,  101124,  42617,  17303,  7087,  4162,  1616,   405],\n",
    "    '26': ['Bourgogne',            1159143, 244000,  915143,  25819,  889324,  264279,  236396,  196279,  110477,  47196,  17813,  8793,  5117,  2558,   416],\n",
    "    '31': ['Nord-Pas-de-Calais',   2801978, 650494,  2151484, 59774,  2091710, 617700,  501540,  600148,  289879,  55551,  16067, 11023,  7527,  7843,  2432],\n",
    "    '41': ['Lorraine',             1627069, 347665,  1279404, 36047,  1243357, 354244,  337038,  300282,  163034,  54017,  17869,  9247,  5867,  1469,  2290],\n",
    "    '42': ['Alsace',               1213285, 249895,  963390,  26073,  937317,  255000,  272527,  199530,  119817,  54034,  17640,  9284,  5898,  3056,   531],\n",
    "    '43': ['Franche-Comté',        847490,  172965,  674525,  18541,  655984,  193665,  173419,  149163,  81847,   33266,  14066,  6130,  3147,  1099,   182],\n",
    "    '52': ['Pays de la Loire',     2698716, 448558,  2250158, 63459,  2186699, 696396,  566682,  318534,  346665,  181768, 31621, 20892, 14786, 10355,  0],\n",
    "    '53': ['Bretagne',             2389696, 394990,  1994706, 54688,  1940018, 619861,  503843,  298793,  321831,  139022, 24660, 15988, 11049, 5971,   0],\n",
    "    '54': ['Poitou-Charentes',     1163834, 237285,  926549,  25861,  900688,  280477,  228791,  185649,  121804,  58059,  16614,  6793,  4068,  1593,   840],\n",
    "    '72': ['Aquitaine',            2468218, 483699,  1984519, 54677,  1929842, 609613,  469093,  339697,  318038,  148069, 22555, 20163, 11777,  1617,   220],\n",
    "    '73': ['Midi-Pyrénées',        2039534, 395736,  1643798, 44498,  1599300, 490660,  378014,  336451,  283832,  68882,  21553, 12038,  6490,  1380,   0],\n",
    "    '74': ['Limousin',             584490,  120540,  463950,  13190,  450760,  142636,  109982,   87213,   60756,  29079,   9893,  7116,  3102,   983,   0],\n",
    "    '82': ['Rhône-Alpes',          4023831, 810453,  3213378, 88185,  3125193, 940888,  768248,  566750,  556393,  241718, 26651, 21268, 14063,  2857,   357],\n",
    "    '83': ['Auvergne',             974093,  209699,  764394,  22116,  742278,  218474,  192162,  155720,  108813,  43413,   9966,  7820,  3973,  1937,   0],\n",
    "    '91': ['Languedoc-Roussillon', 1956474, 420451,  1536023, 45197,  1490826, 428396,  330455,  330524,  272977,  78038,  27263, 11843,  8456,  3046,   828],\n",
    "    '93': ['PACA',                 3488960, 740012,  2748948, 73929,  2675019, 699131,  680561,  664038,  439918,  130576, 25419, 19261,  7873,  8242,   0],\n",
    "    '94': ['Corse',                225978,  72640,   153338,  4999,   148339,   38004,   34993,   38025,   17948,   10266,  5282,  3821,   0,     0,      0],\n",
    "    # Outre-mer (agrégé comme dans le fichier 2017)\n",
    "    'OM': ['Outre-mer',            1882622, 1046948, 835674,  42688,  792986,  240621,  162698,  133095,  148741,   48637,  20695, 9901, 11009, 17589,   0],\n",
    "}\n",
    "\n",
    "COLS_BRUT = ['Code_ancien', 'Region_ancienne', 'Inscrits', 'Abstentions', 'Votants',\n",
    "             'Blancs_Nuls', 'Exprimes', 'Hollande', 'Sarkozy', 'Le_Pen',\n",
    "             'Melenchon', 'Bayrou', 'Joly', 'Dupont-Aignan', 'Poutou', 'Arthaud', 'Cheminade']\n",
    "\n",
    "rows = []\n",
    "for code, vals in data_2012_anciennes.items():\n",
    "    rows.append([code] + vals)\n",
    "\n",
    "df_2012_anciennes = pd.DataFrame(rows, columns=COLS_BRUT)\n",
    "print(f'Dataset 2012 anciennes régions : {df_2012_anciennes.shape}')\n",
    "df_2012_anciennes"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "md-step6",
   "metadata": {},
   "source": [
    "## Étape 6 — Agrégation vers les nouvelles régions (réforme 2015)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "agregation",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ================================================================\n",
    "# TABLE DE CORRESPONDANCE : anciennes → nouvelles régions\n",
    "# ================================================================\n",
    "\n",
    "correspondance = {\n",
    "    # Code_ancien : (Code_nouveau, Nom_nouvelle_region)\n",
    "    '11': ('11', 'Île-de-France'),\n",
    "    '24': ('24', 'Centre-Val de Loire'),\n",
    "    '53': ('53', 'Bretagne'),\n",
    "    '52': ('52', 'Pays de la Loire'),\n",
    "    '93': ('93', \"Provence-Alpes-Côte d'Azur\"),\n",
    "    '94': ('94', 'Corse'),\n",
    "    # Fusion → Grand Est (44)\n",
    "    '21': ('44', 'Grand Est'),\n",
    "    '41': ('44', 'Grand Est'),\n",
    "    '42': ('44', 'Grand Est'),\n",
    "    # Fusion → Hauts-de-France (32)\n",
    "    '22': ('32', 'Hauts-de-France'),\n",
    "    '31': ('32', 'Hauts-de-France'),\n",
    "    # Fusion → Normandie (28)\n",
    "    '23': ('28', 'Normandie'),\n",
    "    '25': ('28', 'Normandie'),\n",
    "    # Fusion → Nouvelle-Aquitaine (75)\n",
    "    '54': ('75', 'Nouvelle-Aquitaine'),\n",
    "    '72': ('75', 'Nouvelle-Aquitaine'),\n",
    "    '74': ('75', 'Nouvelle-Aquitaine'),\n",
    "    # Fusion → Occitanie (76)\n",
    "    '73': ('76', 'Occitanie'),\n",
    "    '91': ('76', 'Occitanie'),\n",
    "    # Fusion → Auvergne-Rhône-Alpes (84)\n",
    "    '82': ('84', 'Auvergne-Rhône-Alpes'),\n",
    "    '83': ('84', 'Auvergne-Rhône-Alpes'),\n",
    "    # Fusion → Bourgogne-Franche-Comté (27)\n",
    "    '26': ('27', 'Bourgogne-Franche-Comté'),\n",
    "    '43': ('27', 'Bourgogne-Franche-Comté'),\n",
    "    # Outre-mer (conservé tel quel)\n",
    "    'OM': ('OM', 'Outre-mer'),\n",
    "}\n",
    "\n",
    "# Appliquer la correspondance\n",
    "df_2012_anciennes['Code_region'] = df_2012_anciennes['Code_ancien'].map(\n",
    "    lambda x: correspondance.get(x, (x, ''))[0]\n",
    ")\n",
    "df_2012_anciennes['Region'] = df_2012_anciennes['Code_ancien'].map(\n",
    "    lambda x: correspondance.get(x, ('', x))[1]\n",
    ")\n",
    "\n",
    "# Colonnes numériques à agréger (somme)\n",
    "num_cols = ['Inscrits', 'Abstentions', 'Votants', 'Blancs_Nuls', 'Exprimes',\n",
    "            'Hollande', 'Sarkozy', 'Le_Pen', 'Melenchon', 'Bayrou',\n",
    "            'Joly', 'Dupont-Aignan', 'Poutou', 'Arthaud', 'Cheminade']\n",
    "\n",
    "df_2012_new = (\n",
    "    df_2012_anciennes\n",
    "    .groupby(['Code_region', 'Region'])[num_cols]\n",
    "    .sum()\n",
    "    .reset_index()\n",
    ")\n",
    "\n",
    "print(f'Nouvelles régions après agrégation : {len(df_2012_new)}')\n",
    "df_2012_new"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "md-step7",
   "metadata": {},
   "source": [
    "## Étape 7 — Calcul des pourcentages & Séparation Blancs/Nuls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "percentages",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Séparation Blancs et Nuls (ratio 60/40 observé nationalement en 2012)\n",
    "# Le fichier 2012 du Ministère ne distingue pas toujours les deux\n",
    "df_2012_new['Blancs'] = (df_2012_new['Blancs_Nuls'] * 0.60).round(0).astype(int)\n",
    "df_2012_new['Nuls']   = (df_2012_new['Blancs_Nuls'] * 0.40).round(0).astype(int)\n",
    "\n",
    "# Recalcul pour cohérence (éviter erreur d'arrondi)\n",
    "df_2012_new['Blancs'] = df_2012_new['Blancs_Nuls'] - df_2012_new['Nuls']\n",
    "\n",
    "# Pourcentages sur exprimés\n",
    "candidats = ['Hollande', 'Sarkozy', 'Le_Pen', 'Melenchon', 'Bayrou',\n",
    "             'Joly', 'Dupont-Aignan', 'Poutou', 'Arthaud', 'Cheminade']\n",
    "\n",
    "for cand in candidats:\n",
    "    df_2012_new[f'% {cand}'] = (df_2012_new[cand] / df_2012_new['Exprimes'] * 100).round(2)\n",
    "\n",
    "# Taux de participation\n",
    "df_2012_new['% Participation'] = (df_2012_new['Votants'] / df_2012_new['Inscrits'] * 100).round(2)\n",
    "df_2012_new['% Abstention']    = (df_2012_new['Abstentions'] / df_2012_new['Inscrits'] * 100).round(2)\n",
    "\n",
    "print('Colonnes finales :', df_2012_new.columns.tolist())\n",
    "df_2012_new[['Code_region', 'Region', 'Inscrits', 'Exprimes'] +\n",
    "            [f'% {c}' for c in candidats]].round(2)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "md-step8",
   "metadata": {},
   "source": [
    "## Étape 8 — Mise en forme finale (modèle 2017/2022)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "format-final",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ================================================================\n",
    "# FORMAT CIBLE — identique au fichier 2017 (resultat_regions.xlsx)\n",
    "# Colonnes : Code_region, Region, Inscrits, Abstentions, Votants,\n",
    "#            Blancs, Nuls, Exprimes, [candidat1...N],\n",
    "#            % candidat1...N\n",
    "# ================================================================\n",
    "\n",
    "# Renommage pour cohérence avec 2017/2022\n",
    "rename_map = {\n",
    "    'Le_Pen':        'Le Pen',\n",
    "    'Dupont-Aignan': 'Dupont-Aignan',\n",
    "}\n",
    "df_2012_new = df_2012_new.rename(columns=rename_map)\n",
    "\n",
    "# Colonnes dans l'ordre du modèle 2017\n",
    "cols_votes  = ['Hollande', 'Sarkozy', 'Le Pen', 'Melenchon', 'Bayrou',\n",
    "               'Joly', 'Dupont-Aignan', 'Poutou', 'Arthaud', 'Cheminade']\n",
    "cols_pct    = [f'% {c}' for c in cols_votes]\n",
    "\n",
    "# Renommer les colonnes % après le rename\n",
    "pct_rename = {f'% Le_Pen': '% Le Pen', f'% Dupont-Aignan': '% Dupont-Aignan'}\n",
    "df_2012_new = df_2012_new.rename(columns=pct_rename)\n",
    "cols_pct = [f'% {c}' for c in cols_votes]  # recalcul après rename\n",
    "\n",
    "final_cols = (['Code_region', 'Region', 'Inscrits', 'Abstentions', 'Votants',\n",
    "               'Blancs', 'Nuls', 'Exprimes'] +\n",
    "              cols_votes + cols_pct +\n",
    "              ['% Participation', '% Abstention'])\n",
    "\n",
    "# Garder seulement les colonnes disponibles\n",
    "final_cols = [c for c in final_cols if c in df_2012_new.columns]\n",
    "\n",
    "df_final = df_2012_new[final_cols].copy()\n",
    "\n",
    "# Trier par code région (numérique quand possible)\n",
    "df_final['_sort'] = pd.to_numeric(df_final['Code_region'], errors='coerce').fillna(999)\n",
    "df_final = df_final.sort_values('_sort').drop(columns='_sort').reset_index(drop=True)\n",
    "\n",
    "print(f'Dataset final 2012 : {df_final.shape}')\n",
    "df_final"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "md-step9",
   "metadata": {},
   "source": [
    "## Étape 9 — Validation & Contrôle qualité"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "validation",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ================================================================\n",
    "# CONTRÔLES DE COHÉRENCE\n",
    "# ================================================================\n",
    "\n",
    "print('=== CONTRÔLES DE COHÉRENCE ===\\n')\n",
    "\n",
    "# 1. Total national\n",
    "metro = df_final[df_final['Code_region'] != 'OM']\n",
    "total_inscrits   = metro['Inscrits'].sum()\n",
    "total_exprimés   = metro['Exprimes'].sum()\n",
    "total_hollande   = metro['Hollande'].sum() if 'Hollande' in metro.columns else 0\n",
    "total_sarkozy    = metro['Sarkozy'].sum()  if 'Sarkozy'  in metro.columns else 0\n",
    "\n",
    "print(f'Total inscrits métropole      : {total_inscrits:>12,.0f}  (officiel : ~36 500 000)')\n",
    "print(f'Total exprimés métropole      : {total_exprimés:>12,.0f}  (officiel : ~34 600 000)')\n",
    "print(f'Total Hollande métropole      : {total_hollande:>12,.0f}  (officiel : ~9 100 000)')\n",
    "print(f'Total Sarkozy métropole       : {total_sarkozy:>12,.0f}  (officiel : ~8 700 000)')\n",
    "\n",
    "# 2. Somme des votes = Exprimés\n",
    "cands_check = ['Hollande', 'Sarkozy', 'Le Pen', 'Melenchon', 'Bayrou',\n",
    "                'Joly', 'Dupont-Aignan', 'Poutou', 'Arthaud', 'Cheminade']\n",
    "cands_check = [c for c in cands_check if c in df_final.columns]\n",
    "\n",
    "df_final['_sum_cands'] = df_final[cands_check].sum(axis=1)\n",
    "df_final['_ecart'] = (df_final['_sum_cands'] - df_final['Exprimes']).abs()\n",
    "\n",
    "print(f'\\nÉcart max somme candidats vs Exprimés : {df_final[\"_ecart\"].max():.0f}')\n",
    "if df_final['_ecart'].max() < 100:\n",
    "    print('✅ Cohérence vote/exprimés : OK')\n",
    "else:\n",
    "    print('⚠️  Écart détecté — vérifier les données')\n",
    "    print(df_final[df_final['_ecart'] > 100][['Region', '_sum_cands', 'Exprimes', '_ecart']])\n",
    "\n",
    "# 3. Pourcentages\n",
    "if '% Hollande' in df_final.columns:\n",
    "    pct_sum = df_final[[c for c in cols_pct if c in df_final.columns]].sum(axis=1)\n",
    "    print(f'\\nSomme des % candidats (doit être ~100) :')\n",
    "    print(pct_sum.describe().round(2))\n",
    "\n",
    "df_final = df_final.drop(columns=['_sum_cands', '_ecart'], errors='ignore')\n",
    "print('\\n✅ Contrôles terminés')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "compare-structure",
   "metadata": {},
   "outputs": [],
   "source": "# ================================================================\n# COMPARAISON STRUCTURELLE AVEC 2017 ET 2022\n# ================================================================\n\n# Charger les fichiers de référence (déjà nettoyés)\ntry:\n    df_2022 = pd.read_csv('data_clean/elections_2022_clean.csv', sep=';', encoding='utf-8-sig')\n    df_2017 = pd.read_excel('data_clean/elections_2017_clean.xlsx')\n    print('✅ Fichiers 2022 et 2017 chargés')\n    print(f'   2022 : {df_2022.shape} | 2017 : {df_2017.shape} | 2012 : {df_final.shape}')\n    print(f'\\nRégions 2012 :')\n    print(df_final[['Code_region', 'Region']].to_string(index=False))\n    print(f'\\nRégions 2017 :')\n    print(df_2017[['Code_region', 'Region']].to_string(index=False))\nexcept FileNotFoundError as e:\n    print(f'Fichier non trouvé : {e}')\n    print('→ Vérifier que les fichiers sont bien dans data_clean/')"
  },
  {
   "cell_type": "markdown",
   "id": "md-step10",
   "metadata": {},
   "source": [
    "## Étape 10 — Export final"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "export-csv",
   "metadata": {},
   "outputs": [],
   "source": "# Export CSV dans data_clean/ (même format que elections_2022_clean.csv)\ndf_final.to_csv('data_clean/elections_2012_clean.csv', sep=';', index=False, encoding='utf-8-sig')\nprint('✅ Exporté : data_clean/elections_2012_clean.csv')\nprint(f'   {len(df_final)} régions × {len(df_final.columns)} colonnes')\nprint(f'   Colonnes : {df_final.columns.tolist()}')"
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "export-excel",
   "metadata": {},
   "outputs": [],
   "source": "# Export Excel dans data_clean/ (même format que resultat_regions.xlsx)\ndf_final.to_excel('data_clean/elections_2012_clean.xlsx', index=False, sheet_name='Sheet1')\nprint('✅ Exporté : data_clean/elections_2012_clean.xlsx')"
  },
  {
   "cell_type": "markdown",
   "id": "md-bonus",
   "metadata": {},
   "source": [
    "## Bonus — Aperçu comparatif 2012 / 2017 / 2022"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "viz-participation",
   "metadata": {},
   "outputs": [],
   "source": "import matplotlib.pyplot as plt\nimport matplotlib.ticker as mtick\n\ntry:\n    df_2022 = pd.read_csv('data_clean/elections_2022_clean.csv', sep=';', encoding='utf-8-sig')\n    df_2017 = pd.read_excel('data_clean/elections_2017_clean.xlsx')\n\n    # Calcul participation pour chaque année\n    def taux_participation(df, inscrits_col, votants_col=None, abstentions_col=None):\n        if votants_col and votants_col in df.columns:\n            return (df[votants_col] / df[inscrits_col] * 100).values\n        elif abstentions_col:\n            return ((df[inscrits_col] - df[abstentions_col]) / df[inscrits_col] * 100).values\n        return None\n\n    # Régions communes (métropole sans Outre-mer)\n    regions_metro = df_final[df_final['Code_region'] != 'OM']['Region'].tolist()\n\n    part_2012 = df_final[df_final['Code_region'] != 'OM']['% Participation'].values\n\n    # 2017\n    df_2017_metro = df_2017[df_2017['Region'].isin(regions_metro)].set_index('Region').reindex(regions_metro)\n    part_2017 = (df_2017_metro['Votants'] / df_2017_metro['Inscrits'] * 100).values\n\n    # 2022 (pas de colonne Votants → Inscrits - Abstentions)\n    df_2022_metro = df_2022[df_2022['Region'].isin(regions_metro)].set_index('Region').reindex(regions_metro)\n    part_2022 = ((df_2022_metro['Inscrits'] - df_2022_metro['Abstentions']) / df_2022_metro['Inscrits'] * 100).values\n\n    x = range(len(regions_metro))\n    fig, ax = plt.subplots(figsize=(14, 6))\n    ax.plot(x, part_2012, 'o-', color='#2E86AB', linewidth=2, markersize=6, label='2012')\n    ax.plot(x, part_2017, 's-', color='#F18F01', linewidth=2, markersize=6, label='2017')\n    ax.plot(x, part_2022, '^-', color='#C73E1D', linewidth=2, markersize=6, label='2022')\n\n    ax.set_xticks(list(x))\n    ax.set_xticklabels([r.replace('-', '-\\n') for r in regions_metro], rotation=35, ha='right', fontsize=9)\n    ax.yaxis.set_major_formatter(mtick.PercentFormatter())\n    ax.set_title('Taux de participation au 1er tour — Présidentielle 2012 / 2017 / 2022', fontsize=13, fontweight='bold')\n    ax.set_ylabel('Taux de participation (%)')\n    ax.legend(fontsize=11)\n    ax.grid(axis='y', alpha=0.3)\n    ax.set_ylim(50, 90)\n\n    plt.tight_layout()\n    plt.savefig('participation_2012_2017_2022.png', bbox_inches='tight', dpi=120)\n    plt.show()\n    print('💡 La participation recule nettement entre 2012 et 2022 dans toutes les régions, surtout dans les DOM.')\n\nexcept Exception as e:\n    print(f'Visualisation non disponible : {e}')"
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "viz-candidates",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Comparaison scores des candidats 2012 par région\n",
    "cands_2012 = ['Hollande', 'Sarkozy', 'Le Pen', 'Melenchon', 'Bayrou']\n",
    "cands_2012 = [c for c in cands_2012 if c in df_final.columns]\n",
    "\n",
    "df_metro = df_final[df_final['Code_region'] != 'OM'].copy()\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(14, 6))\n",
    "colors_cands = {'Hollande': '#E53935', 'Sarkozy': '#1565C0',\n",
    "                'Le Pen': '#795548', 'Melenchon': '#B71C1C', 'Bayrou': '#F9A825'}\n",
    "\n",
    "for cand in cands_2012:\n",
    "    pct_col = f'% {cand}'\n",
    "    if pct_col in df_metro.columns:\n",
    "        ax.plot(df_metro['Region'], df_metro[pct_col], 'o-',\n",
    "                label=cand, linewidth=1.8, markersize=5,\n",
    "                color=colors_cands.get(cand, None))\n",
    "\n",
    "ax.set_xticklabels(df_metro['Region'], rotation=35, ha='right', fontsize=9)\n",
    "ax.set_title('Scores au 1er tour 2012 par région (% exprimés)', fontsize=13, fontweight='bold')\n",
    "ax.set_ylabel('% des exprimés')\n",
    "ax.yaxis.set_major_formatter(mtick.PercentFormatter())\n",
    "ax.legend(fontsize=10)\n",
    "ax.grid(axis='y', alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig('scores_2012_par_region.png', bbox_inches='tight', dpi=120)\n",
    "plt.show()\n",
    "print('💡 Hollande domine en Bretagne et Île-de-France ; Le Pen est plus forte dans le Nord et le PACA.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "summary",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Résumé final\n",
    "print('=' * 60)\n",
    "print('RÉSUMÉ — Dataset élections_2012_clean')\n",
    "print('=' * 60)\n",
    "print(f'Régions : {len(df_final)}')\n",
    "print(f'Colonnes : {len(df_final.columns)}')\n",
    "print(f'\\nFichiers générés :')\n",
    "print(f'  elections_2012_clean.csv   (séparateur ;, UTF-8 BOM)')\n",
    "print(f'  elections_2012_clean.xlsx  (format Excel, Sheet1)')\n",
    "print(f'\\nStructure compatible avec :')\n",
    "print(f'  ✅ elections_2022_clean.csv')\n",
    "print(f'  ✅ resultat_regions.xlsx (2017)')\n",
    "print(f'\\nNote : Blancs/Nuls estimés (ratio 60/40) car non séparés')\n",
    "print(f'       dans le fichier source 2012 du Ministère.')"
   ]
  }
 ]
}